import { notFound } from "next/navigation";
import { and, eq, isNull } from "drizzle-orm";
import { getLocale } from "next-intl/server";
import { db } from "@/lib/db";
import { stores } from "@/lib/db/schema";
import { LegalShell } from "@/components/shared/legal-page";

export const metadata = { title: "Información legal" };

// Página legal autogenerada de cada tienda con los datos que el dueño
// rellena en ajustes. Si faltan datos se muestra el aviso de "pendiente".
export default async function StoreLegalPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const locale = await getLocale();

  const [store] = await db
    .select()
    .from(stores)
    .where(and(eq(stores.slug, slug), isNull(stores.deletedAt)))
    .limit(1);
  if (!store) notFound();

  const name = store.legalName ?? store.name;
  const taxId = store.legalTaxId;
  const address = store.legalAddress;
  const email = store.contactEmail;

  if (locale === "en") {
    return (
      <LegalShell
        title={`Legal information — ${store.name}`}
        updated="Auto-generated by Vendi"
      >
        <h2>Merchant</h2>
        <p>
          This store is operated by {name}
          {taxId ? `, tax ID ${taxId}` : ""}
          {address ? `, with address at ${address}` : ""}.
          {email ? ` Contact: ${email}.` : ""}
        </p>
        {!taxId || !address || !email ? (
          <p>
            Some legal details are pending completion by the merchant. For
            any question, contact the store through its usual channels.
          </p>
        ) : null}
        <h2>Sales, shipping and returns</h2>
        <p>
          The merchant is responsible for fulfilling orders, the announced
          shipping cost and statutory consumer rights, including the right of
          withdrawal within 14 days for distance sales where applicable.
        </p>
        <h2>Payments</h2>
        <p>
          Card payments are processed by Stripe on behalf of the merchant.
          The Vendi platform (Olcas Apps) does not take part in the sales
          contract.
        </p>
      </LegalShell>
    );
  }

  return (
    <LegalShell
      title={`Información legal — ${store.name}`}
      updated="Generado automáticamente por Vendi"
    >
      <h2>Comerciante</h2>
      <p>
        Esta tienda está operada por {name}
        {taxId ? `, NIF ${taxId}` : ""}
        {address ? `, con domicilio en ${address}` : ""}.
        {email ? ` Contacto: ${email}.` : ""}
      </p>
      {!taxId || !address || !email ? (
        <p>
          Algunos datos legales están pendientes de completar por el
          comerciante. Para cualquier consulta, contacta con la tienda por
          sus canales habituales.
        </p>
      ) : null}
      <h2>Ventas, envíos y devoluciones</h2>
      <p>
        El comerciante es responsable de la preparación de los pedidos, del
        coste de envío anunciado y de los derechos de consumo aplicables,
        incluido el derecho de desistimiento de 14 días en ventas a distancia
        cuando proceda.
      </p>
      <h2>Pagos</h2>
      <p>
        Los pagos con tarjeta los procesa Stripe por cuenta del comerciante.
        La plataforma Vendi (Olcas Apps) no es parte del contrato de
        compraventa.
      </p>
    </LegalShell>
  );
}
